[package]
name = "pg-cli"
version = "0.1.0"
edition = "2024"
description = "Generate Kubernetes ConfigMaps from Postgres schema/migration SQL files"

[[bin]]
name = "pg-cli"
path = "src/main.rs"

[dependencies]
pg-gen = { path = "../../../libs/pg-gen" }
clap = { version = "4.6.6", features = ["derive"] }
clap-markdown = "0.1.5"
eyre = "0.6.14"
color-eyre = "0.6.5"
