use std::collections::BTreeMap;
use std::path::Path;

use eyre::{Context, Result};
use serde::Serialize;

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ConfigMapData {
    pub api_version: String,
    pub kind: String,
    pub metadata: ConfigMapMetadata,
    pub data: BTreeMap<String, String>,
}

#[derive(Debug, Serialize)]
pub struct ConfigMapMetadata {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    pub labels: BTreeMap<String, String>,
}

pub struct ConfigMapBuilder {
    name: String,
    namespace: Option<String>,
    labels: BTreeMap<String, String>,
    data: BTreeMap<String, String>,
}

impl ConfigMapBuilder {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            namespace: None,
            labels: BTreeMap::new(),
            data: BTreeMap::new(),
        }
    }

    pub fn namespace(mut self, ns: impl Into<String>) -> Self {
        self.namespace = Some(ns.into());
        self
    }

    pub fn label(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.labels.insert(key.into(), value.into());
        self
    }

    pub fn data_from_file(mut self, key: impl Into<String>, path: &Path) -> Result<Self> {
        let content =
            std::fs::read_to_string(path).wrap_err_with(|| format!("reading {}", path.display()))?;
        self.data.insert(key.into(), content);
        Ok(self)
    }

    pub fn data_from_migration_dir(mut self, dir: &Path) -> Result<Self> {
        if !dir.exists() {
            return Ok(self);
        }
        // Include all *.sql files plus atlas.sum (Atlas operator validates the
        // checksum manifest against every file present in the configmap).
        let mut entries: Vec<_> = std::fs::read_dir(dir)
            .wrap_err_with(|| format!("reading directory {}", dir.display()))?
            .filter_map(|e| e.ok())
            .filter(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                name.ends_with(".sql") || name == "atlas.sum"
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let content = std::fs::read_to_string(entry.path())?;
            let filename = entry.file_name().to_string_lossy().to_string();
            self.data.insert(filename, content);
        }
        Ok(self)
    }

    pub fn build(self) -> ConfigMapData {
        ConfigMapData {
            api_version: "v1".to_string(),
            kind: "ConfigMap".to_string(),
            metadata: ConfigMapMetadata {
                name: self.name,
                namespace: self.namespace,
                labels: self.labels,
            },
            data: self.data,
        }
    }
}

impl ConfigMapData {
    pub fn to_yaml(&self) -> Result<String> {
        let yaml = serde_yaml::to_string(self)?;
        Ok(format!("# Auto-generated by: pg-cli\n{yaml}"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builds_configmap_with_inline_data() {
        let cm = ConfigMapBuilder::new("test-cm")
            .namespace("default")
            .label("app", "test")
            .build();

        assert_eq!(cm.metadata.name, "test-cm");
        assert_eq!(cm.metadata.namespace, Some("default".to_string()));
        assert_eq!(cm.metadata.labels.get("app"), Some(&"test".to_string()));
        assert_eq!(cm.kind, "ConfigMap");
        assert_eq!(cm.api_version, "v1");
    }

    #[test]
    fn serializes_to_yaml() {
        let mut cm = ConfigMapBuilder::new("test-cm")
            .namespace("ns")
            .label("app", "test")
            .build();
        cm.data.insert("key.txt".to_string(), "value".to_string());

        let yaml = cm.to_yaml().unwrap();
        assert!(yaml.contains("# Auto-generated by: pg-cli"));
        assert!(yaml.contains("apiVersion: v1"));
        assert!(yaml.contains("kind: ConfigMap"));
        assert!(yaml.contains("name: test-cm"));
        assert!(yaml.contains("namespace: ns"));
    }
}
