//! Build Kubernetes `ConfigMap` manifests from Postgres schema and migration SQL files.
//!
//! This is the library behind the `pg-cli` binary. Use it directly when you want to
//! generate manifests from Rust instead of shelling out.
//!
//! # Usage
//!
//! Inline data, no filesystem access:
//!
//! ```
//! use pg_gen::ConfigMapBuilder;
//!
//! let mut cm = ConfigMapBuilder::new("mydatabase-schema")
//!     .namespace("dbs")
//!     .label("app.kubernetes.io/name", "mydatabase-schema")
//!     .label("app.kubernetes.io/component", "schema")
//!     .build();
//! cm.data.insert("schema.sql".into(), "CREATE TABLE users (id BIGSERIAL PRIMARY KEY);".into());
//!
//! let yaml = cm.to_yaml().unwrap();
//! assert!(yaml.starts_with("# Auto-generated by: pg-cli\n"));
//! assert!(yaml.contains("kind: ConfigMap"));
//! assert!(yaml.contains("schema.sql: CREATE TABLE users"));
//! ```
//!
//! From files on disk (what `pg-cli configmap schema` / `pg-cli configmap migrations` do):
//!
//! ```no_run
//! use std::path::Path;
//!
//! use pg_gen::ConfigMapBuilder;
//!
//! # fn main() -> eyre::Result<()> {
//! // One key `schema.sql` holding the file contents.
//! let schema = ConfigMapBuilder::new("mydatabase-schema")
//!     .namespace("dbs")
//!     .data_from_file("schema.sql", Path::new("manifests/db/schema.sql"))?
//!     .build();
//!
//! // One key per `*.sql` file (plus `atlas.sum` if present), sorted by filename.
//! // A missing directory yields an empty `data` map rather than an error.
//! let migrations = ConfigMapBuilder::new("mydatabase-migrations")
//!     .data_from_migration_dir(Path::new("manifests/db/migrations"))?
//!     .build();
//!
//! print!("{}---\n{}", schema.to_yaml()?, migrations.to_yaml()?);
//! # Ok(())
//! # }
//! ```
//!
//! Run the compiled example with `cargo run -p pg-gen --example configmap`.
//!
//! # Output shape
//!
//! `ConfigMapData::to_yaml` emits a single `v1/ConfigMap` document prefixed with
//! `# Auto-generated by: pg-cli`. Labels and data keys are emitted in sorted order
//! (`BTreeMap`), so output is deterministic and diff-friendly.

pub mod configmap;

pub use configmap::{ConfigMapBuilder, ConfigMapData};
